### PR TITLE
Chores/add missing device data 

### PR DESCRIPTION
**Pull request by aneyzberg**
**Problem**
We were missing some data from devices and were missing carrier info all together in the SDK. 

**Solution**
Ensure we are sending correct device data back to amplitude. 
We were missing `device_manufacturer` from the payload and were not retrieving `carrier` all together. 
We added back `device_manufacturer` and wrote native extensions to retrieve `carrier` for iOS and Android

**Changes**
1) add `device_manufacturer` back to payload
1) Added channel called `amplitude_flutter` to call into native code in `sim_info.dart`
1) Added `carrierName` and `deviceModel` methods that can be called by that channel in `sim_info.dart`
1) Add native extension in iOS to retrieve `carrier` in `AmplitudeFlutterPlugin.m`
1) Add native extension in Android to retrieve `carrier` in `AmplitudeFlutterPlugin.java`
1) Added functionality in the Java extension to ask permission from users for their carrier info with they are running Android SDK >= 23
1) Added specs to make sure channel set up correctly
1) Added a flag to turn retrieving carrier info on and off. See README for instructions.

**Steps to Verify** 
1) clone the project
2) cd into `example`
3) run `flutter packages get`
4) run `flutter run`

### CODE REVIEW

**Comment by aneyzberg** [comment]
@haoliu-amp happy to jump on a call if you would like to go this PR and answer any questions you might have

**Comment by haoliu-amp** [comment]
Thanks! I will take a look and do some tests around it. Will let you know if I do have questions.

**Comment by haoliu-amp** [comment]
Ah sorry, I accidentally closed it, can you reopen it? @aneyzberg

**Comment by aneyzberg** [comment]
@haoliu-amp - just wanted to let you know that today is my last day on the project. So am happy to address any feedback or hop on a call to do a knowledge transfer for the work done. Just let me know.

**Comment by haoliu-amp** [comment]
Thanks for your help @aneyzberg !

**Pull request merged**
